[workspace]
resolver = "2"

members = [
    "epserde-derive",
    "epserde",
]

[workspace.dependencies]
epserde = { path="./epserde" }
epserde-derive = { path="./epserde-derive", version = "0.12.0" }
